name: Dockerfile to GitHub Pages

on:
  push:
    branches: [ "master" ]  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Docker
        env:
          JEKYLL_ENV: production  # set environment variable
        run: |
          docker run --rm \
            -v "$PWD:/srv/jekyll" \  
            -e JEKYLL_ENV=$JEKYLL_ENV \     #express environment variable
            jekyll/jekyll:latest \
            jekyll build                    #conduct setting commands

      - name: Dockerfile to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: ./_site  # Jekyll default output catalogue
